config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "gps#index"
  
  authenticated :user do
    scope '/admin' do
      resources :bus_stops
      resources :trips
      resources :buses
    end

    resources :gps, only: [:index]
    
    post '/gps/find_bus', to: 'gps#find_bus', as: "find_bus"
    get '/gps/find_bus', to: 'gps#index', as: "find_bus_index"
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  MINIMUM_BUS_INTERVAL = 10
  TRIPS_START_TIME = Time.parse("6:00")
  TRIPS_FINISH_TIME = Time.parse("22:00")

  has_many :schedules, :class_name => 'Schedule'
  has_many :buses, :class_name => 'Bus'
  has_many :trip_bus_stop
  has_many :bus_stops, through: :trip_bus_stop

  validates :identifier, presence: true, uniqueness: true, numericality: true
  validates :trip_bus_stop, length: { minimum: 2, maximum: 10 }

  def duration
    (0..(bus_stops.length - 2)).inject(0) do |sum_duration, index|
      start_stop = bus_stops[index]
      end_stop = bus_stops[index+1]

      sum_duration + duration_two_ways(start_stop, end_stop)
    end
  end

  def half_way_duration
    (0..(bus_stops.length - 2)).inject(0) do |sum_duration, index|
      start_stop = bus_stops[index]
      end_stop = bus_stops[index+1]
      
      connection = Connection.where(start_stop: start_stop, end_stop: end_stop).first
      sum_duration + connection.trip_duration.minutes
    end
  end

  def duration_and_resting
    duration + resting_time
  end

  def resting_time
    rest = (duration/60) % 10
    (10 - rest).minutes
  end

  private

  def get_buses_schedule
    buses.map do |bus|
      bus.depart_time
    end
  end

  def duration_two_ways(start_stop, end_stop)
    connection_from_station = Connection.where(start_stop: start_stop, end_stop: end_stop).first
    connection_to_station = Connection.where(start_stop: end_stop, end_stop: start_stop).first
    raise "no_connection_found" unless connection_from_station && connection_from_station
    
    connection_from_station.trip_duration.minutes + connection_to_station.trip_duration.minutes
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :authorize_can_can

  def index
    @trips = Trip.all
  end

  def show
  end

  def new
    @trip = Trip.new
    get_bus_stops
    @selected_bus_stops = []
  end

  def create
    @selected_bus_stops = []
    @trip = BuildTrip.call(params: trip_params).trip
    
    respond_to do |format|
      save_trip(format, 'Trip was successfully created.')
    end
  end

  def edit
    edit_and_update_setup
  end

  def update
    edit_and_update_setup
    
    UpdateTrip.call(trip: @trip, params: trip_params)

    respond_to do |format|
      save_trip(format, 'Trip was successfully updated.')
    end
  end

  def destroy
    @trip.trip_bus_stop.destroy_all
    @trip.schedules.destroy_all
    @trip.destroy
    
    redirect_to trips_path
  end

  private

  def save_trip(format, message)
    if @trip.save
      BuildConnections.call(bus_stops: @trip.bus_stops)
      BuildSchedules.call(trip: @trip)
      
      format.html { redirect_to action: "index" }
      format.json { render json: Trip.all.order(:identifier) }
    else
      format.html { render :edit }
      format.json { render json: @trip.errors, status: :unprocessable_entity }
    end
  end

  def edit_and_update_setup
    get_bus_stops
    @selected_bus_stops = @trip.bus_stops
    selected_bus_stops_ids = @selected_bus_stops.map(&:id)
    @bus_stops = @bus_stops.select { |bs| !selected_bus_stops_ids.include?(bs.id) }
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def get_bus_stops
    @bus_stops = BusStop.all
    @trip_bus_stop = @trip.trip_bus_stop.build
  end

  def trip_params
    params.require(:trip).permit(:identifier, :bus_stops => [])
  end

  def authorize_can_can
    authorize! :mana, :all
  end
end

app/helpers/trip_helper.rb
module TripHelper
end

app/views/trips/_form.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>
    <style>
      .subject-info-box-1,
        .subject-info-box-2 {
            float: left;
            width: 45%;
            
            select {
                height: 200px;
                padding: 0;
                option {
                    padding: 4px 10px 4px 10px;
                }
                option:hover {
                    background: #EEEEEE;
                }
            }
        }
        .subject-info-arrows {
            float: left;
            width: 10%;
            input {
                width: 70%;
                margin-bottom: 5px;
            }
        }
    </style>
    
    <script>
      function btnRightClick(e) {
        var selectedOpts = $('#lstBox1 option:selected');
        if (selectedOpts.length == 0) {
            alert("Nothing to move.");
            e.preventDefault();
        }
        $('#lstBox2').append($(selectedOpts).clone());
        $(selectedOpts).remove();
      };

      function btnLeftClick(e) {
        var selectedOpts = $('#lstBox2 option:selected');
        if (selectedOpts.length == 0) {
            alert("Nothing to move.");
            e.preventDefault();
        }
        $('#lstBox1').append($(selectedOpts).clone());
        $(selectedOpts).remove();
      };
    </script>
    
    <div class="container">
      <div class="row">
        <%= form_with model: @trip, local: true do |form| %> 
          <% if @trip.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@trip.errors.count, "error") %> prohibited
                this trip from being saved:
              </h2>
              <ul>
                <% @trip.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="col s4">
              <h4>Identifier </h4>
                <%= form.number_field :identifier, :value => @trip.identifier %>
            </div>
          </div>
          <h4>Choose the bus station </h4>
          <div class="subject-info-box-1">
            <%= form.select( :bus_stops_to_choose, @bus_stops.collect {|p| [p.identifier, p.id ]}, { :selected => "" }, { :multiple => "true", :id => "lstBox1" } )%>
          </div>
          <div class="subject-info-arrows text-center">
            <input type="button" id="btnRight" value=">" class="btn btn-default" onclick="btnRightClick(this)" /><br />
            <input type="button" id="btnLeft" value="<" class="btn btn-default" onclick="btnLeftClick(this)" /><br />
          </div>
          <div class="subject-info-box-2">
            <%= form.select( :bus_stops, @selected_bus_stops.collect {|p| [p.identifier, p.id ]}, { :selected => "" }, { :multiple => "true", :id => "lstBox2" } )%>
          </div>
          <div class="clearfix"></div>
          <%= form.submit("Submit Trip", class: "waves-effect waves-light btn-large") %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/trips/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit Trip</h1>
    <h2>If edit you will need to realocate all buses for this trip</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/trips/index.html.erb
<div class="container">
  <div class="row">
    <ul class="collection with-header">
      <li class="collection-header">
        <div>
          <h4>Trips</h4>
        <div>
      </li>
      <% @trips.each do |trip| %>
      <li class="collection-item">
        <div>
          <%= trip.identifier %>
          <a href=<%= edit_trip_path(trip) %> class="secondary-content">
            <i class="material-icons">mode_edit</i>
          </a>
          <%= link_to 'delete', 
             trip_path(trip), 
                         method: :delete, 
                         data: { confirm: 'Are you sure?' },
                         class: "secondary-content material-icons" %>
        </div>
      </li>
      <% end %>
    </ul>

    <a href=<%= new_trip_path %> class="btn-floating btn-large waves-effect waves-light"><i class="material-icons">add</i></a>
  </div>
</div>

app/views/trips/new.html.erb
<div class="container">
  <div class="row">
    <h1>New Trip</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/trips/show.html.erb
<p>
  <strong>Identifier:</strong>
  <%= @trip.identifier %>
</p>
<%= link_to 'Edit', edit_trip_path(@trip) %>
<%= link_to 'Back', trips_path %>