config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "gps#index"
  
  authenticated :user do
    scope '/admin' do
      resources :bus_stops
      resources :trips
      resources :buses
    end

    resources :gps, only: [:index]
    
    post '/gps/find_bus', to: 'gps#find_bus', as: "find_bus"
    get '/gps/find_bus', to: 'gps#index', as: "find_bus_index"
  end
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]
  before_action :authorize_can_can

  def index
    @buses = Bus.all
  end

  def show
  end

  def new
    new_setup
  end

  def create
    new_setup
    @bus = Bus.new(registration_number: bus_params[:registration_number])

    @bus.trip = Trip.find(bus_params[:trip])
    @bus.schedule = Schedule.find(bus_params[:schedule])

    respond_to do |format|
      save_bus(format, 'Bus was successfully created.')
    end
  end

  def edit
    edit_setup
  end

  def update
    edit_setup
    @bus.registration_number = bus_params[:registration_number]
    @bus.trip = Trip.find(bus_params[:trip])
    @bus.schedule = Schedule.find(bus_params[:schedule])

    respond_to do |format|
      save_bus(format, 'Bus was successfully updated.')
    end
  end

  def destroy
    @bus.destroy
    
    redirect_to buses_path
  end

  private

  def save_bus(format, message)
    if @bus.save      
      format.html { redirect_to action: "index" }
      format.json { render json: Bus.all.order(:registration_number) }
    else
      format.html { render :edit }
      format.json { render json: @bus.errors, status: :unprocessable_entity }
    end
  end

  def set_bus
    @bus = Bus.find(params[:id])
  end

  def new_setup
    @bus = Bus.new
    get_trips
    build_trips_schedules

    @trip_id = "null"
    @schedule_id = "null"
  end

  def edit_setup
    get_trips
    build_trips_schedules

    @trip_id = @bus.trip.try(:id)
    @schedule_id = @bus.schedule.try(:id)
  end

  def get_trips
    @trips = Trip.all
  end

  def build_trips_schedules
    @trips_schedules = {}
    @trips.each do |trip|
      @trips_schedules[:"#{trip.id}"] = trip.schedules
    end
  end

  def bus_params
    params.require(:bus).permit(:registration_number, :trip, :schedule)
  end

  def authorize_can_can
    authorize! :mana, :all
  end
end

app/views/buses/_form.html.erb
<script>
    function select_trip(selectElem) {
      var trip_id = selectElem.options[selectElem.selectedIndex].value;
      console.log(trip_id)
      var previous_schedules = document.getElementsByClassName("schedules-dropdown");

      for (var i = 0; i < previous_schedules.length; i++) {
        previous_schedules[i].style.display = 'none';
      }
      
      document.getElementById("dropdown_schedules_"+trip_id).style.display = 'block';
    };

    $(document).ready(function(){
      trip_id = <%= @trip_id || "null" %>
      schedule_id = <%= @schedule_id || "null" %>

      if(trip_id !== null && schedule_id !== null){
        document.getElementById("dropdown_trips").value = trip_id;
        document.getElementById("dropdown_schedules_"+trip_id).style.display = 'block';

        var dropdows = document.getElementsByClassName("dropdown_schedule");
        for (var i = 0; i < dropdows.length; i++) {
          if(dropdows[i].parentNode.style.display === 'block'){
            dropdows[i].value = schedule_id;
          }
        }
      }
    });
</script>

<body>
  <div class="container">
    <div class="row">
      <%= form_with model: @bus, local: true do |form| %> 
        <% if @bus.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@bus.errors.count, "error") %> prohibited
              this bus from being saved:
            </h2>
            <ul>
              <% @bus.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row">
          <div class="col s4">
            <h4>Registration Number </h4>
              <%= form.text_field :registration_number, :value => @bus.registration_number %>
          </div>
        </div>
        <div class="row">
          <div class="col s4">
            <div class="trips-dropdown" >
              <%= form.collection_select :trip, @trips || [], 
                :id, :identifier,
                  { include_blank: '', multiple: false }, { :id => "dropdown_trips",  :onchange => "select_trip(this)" } %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col s4">
            <% @trips_schedules.each do |key, schedules| %>
              <div class="schedules-dropdown" style="display:none" id=<%="dropdown_schedules_#{key}"%> >
                <%= form.collection_select :schedule, schedules || [], 
                  :id, :schedule_time_range,
                    { multiple: false }, { class: "dropdown_schedule" }%>
                <p>
              </div>
            <% end %>
          </div>
        </div>
        <%= form.submit("Submit Bus", class: "waves-effect waves-light btn-large") %>
      <% end %>
    </div>
  </div>
</body>

app/views/buses/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit Bus</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/buses/index.html.erb
<div class="container">
  <div class="row">
    <ul class="collection with-header">
      <li class="collection-header">
        <div>
          <h4>Buses</h4>
        <div>
      </li>
      <% @buses.each do |bus| %>
      <li class="collection-item">
        <div>
          <strong>Registration number</strong><%= ": #{bus.registration_number}" %>
          <strong>Trip</strong><%= ": #{bus.trip ? bus.trip.identifier : 'None'}" %>
          <strong>Schedule</strong><%= ": #{bus.schedule ? bus.schedule.schedule_time_range : 'None'}"  %>
          <a href=<%= edit_bus_path(bus) %> class="secondary-content">
            <i class="material-icons">mode_edit</i>
          </a>
          <%= link_to 'delete', 
             bus_path(bus), 
                         method: :delete, 
                         data: { confirm: 'Are you sure?' },
                         class: "secondary-content material-icons" %>
        </div>
      </li>
      <% end %>
    </ul>

    <a href=<%= new_bus_path %> class="btn-floating btn-large waves-effect waves-light"><i class="material-icons">add</i></a>
  </div>
</div>

app/views/buses/new.html.erb
<div class="container">
  <div class="row">
    <h1>New Bus</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/buses/show.html.erb
<p>
  <strong>Registration number:</strong>
  <%= @bus.registration_number %>
</p>
<%= link_to 'Edit', edit_bus_path(@bus) %>
<%= link_to 'Back', buses_path %>