config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "gps#index"
  
  authenticated :user do
    scope '/admin' do
      resources :bus_stops
      resources :trips
      resources :buses
    end

    resources :gps, only: [:index]
    
    post '/gps/find_bus', to: 'gps#find_bus', as: "find_bus"
    get '/gps/find_bus', to: 'gps#index', as: "find_bus_index"
  end
end

app/models/bus_stop.rb
class BusStop < ApplicationRecord
  has_many :trip_bus_stop
  has_many :trips, through: :trip_bus_stop
  has_many :connections, :class_name => 'Connection', :foreign_key => 'connection_id'
  
  validates :identifier, presence: true, uniqueness: true, numericality: true
  validates_numericality_of :identifier
end

app/controllers/bus_stops_controller.rb
class BusStopsController < ApplicationController
  before_action :set_bus_stop, only: [:show, :edit, :update, :destroy]
  before_action :authorize_can_can

  def index
    @bus_stops = BusStop.all
  end

  def show
  end

  def new
    @bus_stop = BusStop.new
  end

  def create
    @bus_stop = BusStop.new(bus_stop_params)

    respond_to do |format|
      save_bus_stop(format, 'Bus stop was successfully created.')
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      save_bus_stop(format, 'Bus stop was successfully updated.')
    end
  end

  def destroy
    @bus_stop.trip_bus_stop.destroy_all
    @bus_stop.destroy
    
    redirect_to bus_stops_path
  end

  private

  def save_bus_stop(format, message)
    if @bus_stop.save      
      format.html { redirect_to action: "index" }
      format.json { render json: BusStop.all.order(:identifier) }
    else
      format.html { render :edit }
      format.json { render json: @bus_stop.errors, status: :unprocessable_entity }
    end
  end

  def set_bus_stop
    @bus_stop = BusStop.find(params[:id])
  end

  def bus_stop_params
    params.require(:bus_stop).permit(:identifier)
  end

  def authorize_can_can
    authorize! :mana, :all
  end
end

app/helpers/bus_stop_helper.rb
module BusStopHelper
end

app/views/bus_stops/_form.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="container">
      <div class="row">
        <%= form_with model: @bus_stop, local: true do |form| %> 
          <% if @bus_stop.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@bus_stop.errors.count, "error") %> prohibited
                this bus_stop from being saved:
              </h2>
              <ul>
                <% @bus_stop.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="col s4">
              <h4>Identifier </h4>
                <%= form.number_field :identifier, :value => @bus_stop.identifier %>
            </div>
          </div>
          <%= form.submit("Submit Bus Stop", class: "waves-effect waves-light btn-large") %>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/bus_stops/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit Bus Stop</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/bus_stops/index.html.erb
<div class="container">
  <div class="row">
    <ul class="collection with-header">
      <li class="collection-header">
        <div>
          <h4>Bus Stops</h4>
        <div>
      </li>
      <% @bus_stops.each do |bus_stop| %>
      <li class="collection-item">
        <div>
          <%= bus_stop.identifier %>
          <a href=<%= edit_bus_stop_path(bus_stop) %> class="secondary-content">
            <i class="material-icons">mode_edit</i>
          </a>
          <%= link_to 'delete', 
             bus_stop_path(bus_stop), 
                         method: :delete, 
                         data: { confirm: 'Are you sure?' },
                         class: "secondary-content material-icons" %>
        </div>
      </li>
      <% end %>
    </ul>

    <a href=<%= new_bus_stop_path %> class="btn-floating btn-large waves-effect waves-light"><i class="material-icons">add</i></a>
  </div>
</div>

app/views/bus_stops/new.html.erb
<div class="container">
  <div class="row">
    <h1>New Bus Stop</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/bus_stops/show.html.erb
<p>
  <strong>Identifier:</strong>
  <%= @bus_stop.identifier %>
</p>
<%= link_to 'Edit', edit_bus_stop_path(@bus_stop) %>
<%= link_to 'Back', bus_stops_path %>